option('systemd-logs',
  type: 'feature',
  description: 'Hide timestamps in log messages, needed for systemd')

option('systemd-unit-dir',
  type: 'string',
  value: '',
  description: 'Directory for systemd service files (leave empty for auto-detection)')

option('nls',
  type: 'feature',
  description: 'Enable message translations')

option('udev-rules-dir',
  type: 'string',
  value: '',
  description: 'Directory for udev rules (leave empty for auto-detection)')

option('input-group',
  type: 'string', value: 'plugdev',
  description: 'Group for input devices')

option('lipc_examples',
  type: 'boolean',
  value: false,
  description: 'Build localipc example programs')
