FROM archlinux:base-devel

LABEL org.opencontainers.image.description="INTERNAL CI USE ONLY - Not intended for production"
LABEL org.opencontainers.image.authors="Nirenjan Krishnan"

COPY ./install-dependencies-archlinux.sh ./ci-setup.sh /tmp/

RUN /tmp/install-dependencies-archlinux.sh && /tmp/ci-setup.sh
