i18n.gettext(meson.project_name(),
    args: [
        '--directory=' + meson.project_source_root(),
        '--msgid-bugs-address=https://github.com/nirenjan/libx52/issues',
        '--package-name=' + meson.project_name(),
        '--package-version=' + meson.project_version(),
        '--copyright-holder=Nirenjan Krishnan',
        '--keyword=_', '--keyword=N_',
    ],
    languages: [
        'xx_PL',
    ],
    install: true,
)
